version: "2.1"

services:
  bot:
    container_name: exchange-rate-bot
    build:
      context: .
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - MONGODB_URI=mongodb://mongo:27017/exchange-rate
      # Если используете вебхук/HTTP:
      # - PORT=3000
      # - PUBLIC_URL=${PUBLIC_URL}
    depends_on:
      - mongo
    restart: always
    # Если есть HTTP-порт, раскомментируйте:
    # ports:
    #   - "3000:3000"
    # Логи/кеш во внешний том (опционально):
    # volumes:
    #   - bot-logs:/app/logs

  mongo:
    image: mongo:7
    container_name: mongo
    command: ["--bind_ip_all"]
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    restart: always

  mongo-express:
    image: mongo-express:1
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
      - ME_CONFIG_BASICAUTH=true
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_USERNAME:-admin}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_PASSWORD:-admin}
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    restart: always

volumes:
  mongo-data: {}
  # bot-logs: {}
